export const ROUTE_STRINGS = {
    HOME : 'homepage',
}

export const HOME_PAGE = {
    PROFILE_IMAGE : 'assets/ProfileImage.png',
    PROFILE_IMAGE_ALT : 'Profile',
    POST_BUTTON_TEXT : 'We are hiring talented individuals from our trusted circle',
    CARD_TITLE : 'Innovapptive',
    CARD_TITLE_DESCRIPTION : 'Innovapptive - Hiring',
    SEE_MORE : '...See More',
    SEE_LESS : 'See Less',
    COMMENT_TEXT : 'Comment',
    COMMENT_ICON : 'comment',
    SEND_TEXT: 'Send',
    SEND_ICON : 'send',
    THUMS_UP_ICON : 'thumb_up',
    LIKE_TEXT : 'Like',
    INNOVAPPTIVE_POSTS : 'innovapptive Job Openings'


    // DETAILS : [
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //     { title: 'Panel 1', description: 'I am the first panel', imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 2', description: 'I am the second panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 3', description: 'I am the third panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 4', description: 'I am the fourth panel',  imageUrl:'/assets/SampleImage.png' },
    //     { title: 'Panel 5', description: 'I am the fifth panel',  imageUrl:'/assets/SampleImage.png'},
    //   ]
}

export const POST_FORM = {
    CLOSE : 'Close',
    SAVE : 'Save',
    PROFILE_IMAGE_ALT : 'Profile',
    PROFILE_IMAGE : 'assets/ProfileImage.png',
    TEXT_PLACEHOLDER : 'What do you want to talk about?',
    INNOVAPPTIVE : 'Innovapptive',
    POST_EVERY_THING : 'Lets Hire!!',
    SATISFIED_ICON : 'sentiment_satisfied_alt',
    SELECT_IMAGE_DIRECTION : 'Select the Image>>',
    BROWSE : 'browse',
    DROP : 'drop or',
    UPLOAD_PNG : 'png / jpg file to upload',
    PHOTO_LIBRARY_ICON : 'photo_library',
    POST_BUTTON_TEXT : 'Post',
    TEXTAREA_MAX_LENGTH : 1000

}

